### ISSUE TITLE
Can't seem to get it to do anything

### ISSUE THREAD

**Issue by greglow-sdu** [mjisaak/mvp-docs-learn-champion-extension#16]
Hi Folks, 

Love the idea of this but for the life of me, I can't seem to get it to do anything. I've made a short video of me configuring and trying it, and how nothing happens. Any clues would be useful.

https://sqldownunder.blob.core.windows.net/publicsharing/MVPDocsExtensionIssue.mp4

Regards,

Greg

**Comment by mjisaak** [comment]
hi Greg,

thank you for your interest in the extension and thank you also for the video. You really did everything right (CreatorID was set and the link is also trackable in relation to the Docs&Learn Champion program).  
For me, the link is working:

![image](https://user-images.githubusercontent.com/8446917/111757069-370f7380-889b-11eb-80ca-16a9c04968da.png)

So it seems like it is a bug. I will try to install the same extensions that you have so maybe I will be able to reproduce it. 
Have you tried to reinstall the extension?

Best regards,
Martin

**Comment by greglow-sdu** [comment]
Hi Martin,

Have removed it and re-added it. Seems to be going again. Will let you know if it stops again.

Regards,

Greg

Dr Greg Low

1300SQLSQL (1300 775 775) office | +61 419201410 mobile│ +61 3 8676 4913 fax
SQL Down Under | Web: www.sqldownunder.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.sqldownunder.com%2F&data=02%7C01%7Csspahelp%40microsoft.com%7C1f0ea4d6b97e4d897f3708d666d1e890%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636809449091516274&sdata=SLHeEGAMmWUY5YIwcC4oAPYr%2F9RIZdi4MNASsdzwX2I%3D&reserved=0> |http://greglow.me<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgreglow.me%2F&data=02%7C01%7Csspahelp%40microsoft.com%7C1f0ea4d6b97e4d897f3708d666d1e890%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636809449091526278&sdata=IU8tnAITCjBxWafi3A9XpO9lF3PIwZJ8ad3t36lnxvs%3D&reserved=0>
