### ISSUE TITLE
Feature Request: Context Menu support

### ISSUE THREAD

**Issue by arafattehsin** [mjisaak/mvp-docs-learn-champion-extension#23]
Fantastic work @mjisaak and the team such a great extension. I recently came across this scenario and thought to open up a feature request;

Currently, if I'm already on a webpage and if I right click, I do not get an option of `Copy link address with Creator ID` 

![image](https://user-images.githubusercontent.com/16351038/135951740-6cf8f6dd-c40b-483d-9156-4e2574bc03d8.png)

It would be great if we can have that option as well so that we can directly copy it while reading the docs (or if we think this deserves a share 😉). Probably, something for the `hacktoberfest` 👩‍💻👨‍💻

**Comment by mjisaak** [comment]
@arafattehsin Thanks for the feature request and your kind comment - glad you like the extension. 

Actually, there is already a discussion about that topic: #4 
I will try my best to implement it soon, or will gladly accept PRs for that!
