### ISSUE TITLE
Not showing when right-clicking on Feedly links

### ISSUE THREAD

**Issue by flcdrg** [mjisaak/mvp-docs-learn-champion-extension#5]
Not sure what Feedly.com is doing, but right-clicking on the post headings just shows the regular menu without the MVP option

![image](https://user-images.githubusercontent.com/384747/98748749-37d65b80-240a-11eb-8f61-3c6fe1e23c45.png)

![image](https://user-images.githubusercontent.com/384747/98748825-66eccd00-240a-11eb-8e96-8457c004b135.png)

If I go to a regular web page (outside of Feedly.com) and right-click on a link, then I do get the MVP menu option.

**Comment by mjisaak** [comment]
hi David,

the extension does only show the menu on sites that are tracked by the docks and learn champion program:

- "http://social.technet.microsoft.com/*",
- "https://docs.microsoft.com/*",
- "https://azure.microsoft.com/*",
- "https://techcommunity.microsoft.com/*",
- "https://social.msdn.microsoft.com/*",
- "https://devblogs.microsoft.com/*",
- "https://developer.microsoft.com/*",
- "https://channel9.msdn.com/*",
- "https://gallery.technet.microsoft.com/*",
- "https://cloudblogs.microsoft.com/*",
- "https://technet.microsoft.com/*",
- "https://docs.azure.cn/*",
- "https://www.azure.cn/*",
- "https://msdn.microsoft.com/*",
- "https://blogs.msdn.microsoft.com/*",
- "https://blogs.technet.microsoft.com/*",
- "https://microsoft.com/handsonlabs/*" 

So right now it will not work on Feedly.com. However, maybe within the next version, I can include an option to display it on every site.

**Comment by flcdrg** [comment]
oh.. so it's checking the current page's URL to determine whether to appear or not (rather than checking the URL that's being right-clicked on)

**Comment by mjisaak** [comment]
v
